# Cleaning & Get info about dataset

## Import Libraries

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
plt.style.use("seaborn-v0_8")

## Load data

In [16]:
data = pd.read_csv(
    r"C:\Users\USER\Analytics Projects\Supply_Chain_Analysis\Data\Grocery_Inventory_and_Sales_Dataset.csv",
    encoding='utf-8-sig'
)

print(data.head())

    Product_ID     Product_Name             Catagory  Supplier_ID  \
0  29-205-1132       Sushi Rice      Grains & Pulses  38-037-1699
1  40-681-9981   Arabica Coffee            Beverages  54-470-2479
2  06-955-3428       Black Rice      Grains & Pulses  54-031-2945
3  71-594-6552  Long Grain Rice      Grains & Pulses  63-492-7603
4  57-437-1828             Plum  Fruits & Vegetables  54-226-4308

  Supplier_Name  Stock_Quantity  Reorder_Level  Reorder_Quantity Unit_Price  \
0     Jaxnation              22             72                70     $4.50
1       Feedmix              45             77                 2    $20.00
2        Vinder              30             38                83     $6.00
3    Brightbean              12             59                62     $1.50
4    Topicstorm              37             30                74     $4.00

  Date_Received Last_Order_Date Expiration_Date      Warehouse_Location  \
0     8/16/2024       6/29/2024       9/19/2024        48 Del Sol Trail
1     11/1/2024       5/29/2024        5/8/2024            36 3rd Place
2      8/3/2024       6/10/2024       9/22/2024       3296 Walton Court
3     12/8/2024       2/19/2025       4/17/2024  3 Westerfield Crossing
4      7/3/2024      10/11/2024       10/5/2024    15068 Scoville Court

   Sales_Volume  Inventory_Turnover_Rate        Status
0            32                       19  Discontinued
1            85                        1  Discontinued
2            31                       34   Backordered
3            95                       99        Active
4            62                       25   Backordered

In [27]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 990 entries, 0 to 989
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Product_ID               990 non-null    object
 1   Product_Name             990 non-null    object
 2   Catagory                 989 non-null    object
 3   Supplier_ID              990 non-null    object
 4   Supplier_Name            990 non-null    object
 5   Stock_Quantity           990 non-null    int64
 6   Reorder_Level            990 non-null    int64
 7   Reorder_Quantity         990 non-null    int64
 8   Unit_Price               990 non-null    float64
 9   Date_Received            990 non-null    datetime64[ns]
 10  Last_Order_Date          990 non-null    datetime64[ns]
 11  Expiration_Date          990 non-null    datetime64[ns]
 12  Warehouse_Location       990 non-null    object
 13  Sales_Volume             990 non-null    int64
 14  Inventory_Turnover_Rate  990 non-null    int64
 15  Status                   990 non-null    object
 16  Days_to_Expiry           990 non-null    int64
dtypes: datetime64[ns](3), float64(1), int64(6), object(7)
memory usage: 131.6+ KB
None

## clean column price

In [ ]:
data["Unit_Price"]=data["Unit_Price"].str.replace("$","").astype(float)

## Convert dates to datetime

In [24]:
date_cols = ["Date_Received", "Last_Order_Date", "Expiration_Date"]
for col in date_cols:
    data[col] = pd.to_datetime(data[col])
data.head()

,Product_ID,Product_Name,Catagory,Supplier_ID,Supplier_Name,Stock_Quantity,Reorder_Level,Reorder_Quantity,Unit_Price,Date_Received,Last_Order_Date,Expiration_Date,Warehouse_Location,Sales_Volume,Inventory_Turnover_Rate,Status,Days_to_Expiry
0,29-205-1132,Sushi Rice,Grains & Pulses,38-037-1699,Jaxnation,22,72,70,4.5,2024-08-16,2024-06-29,2024-09-19,48 Del Sol Trail,32,19,Discontinued,34
1,40-681-9981,Arabica Coffee,Beverages,54-470-2479,Feedmix,45,77,2,20.0,2024-11-01,2024-05-29,2024-05-08,36 3rd Place,85,1,Discontinued,-177
2,06-955-3428,Black Rice,Grains & Pulses,54-031-2945,Vinder,30,38,83,6.0,2024-08-03,2024-06-10,2024-09-22,3296 Walton Court,31,34,Backordered,50
3,71-594-6552,Long Grain Rice,Grains & Pulses,63-492-7603,Brightbean,12,59,62,1.5,2024-12-08,2025-02-19,2024-04-17,3 Westerfield Crossing,95,99,Active,-235
4,57-437-1828,Plum,Fruits & Vegetables,54-226-4308,Topicstorm,37,30,74,4.0,2024-07-03,2024-10-11,2024-10-05,15068 Scoville Court,62,25,Backordered,94

## Check missing values

In [22]:
data.isna().sum()

Product_ID                 0
Product_Name               0
Catagory                   1
Supplier_ID                0
Supplier_Name              0
Stock_Quantity             0
Reorder_Level              0
Reorder_Quantity           0
Unit_Price                 0
Date_Received              0
Last_Order_Date            0
Expiration_Date            0
Warehouse_Location         0
Sales_Volume               0
Inventory_Turnover_Rate    0
Status                     0
dtype: int64

## Calculate days until expiry

In [29]:
data["Days_to_Expiry"] = (data["Expiration_Date"] - data["Date_Received"]).dt.days
data.head()

,Product_ID,Product_Name,Catagory,Supplier_ID,Supplier_Name,Stock_Quantity,Reorder_Level,Reorder_Quantity,Unit_Price,Date_Received,Last_Order_Date,Expiration_Date,Warehouse_Location,Sales_Volume,Inventory_Turnover_Rate,Status,Days_to_Expiry
0,29-205-1132,Sushi Rice,Grains & Pulses,38-037-1699,Jaxnation,22,72,70,4.5,2024-08-16,2024-06-29,2024-09-19,48 Del Sol Trail,32,19,Discontinued,34
1,40-681-9981,Arabica Coffee,Beverages,54-470-2479,Feedmix,45,77,2,20.0,2024-11-01,2024-05-29,2024-05-08,36 3rd Place,85,1,Discontinued,-177
2,06-955-3428,Black Rice,Grains & Pulses,54-031-2945,Vinder,30,38,83,6.0,2024-08-03,2024-06-10,2024-09-22,3296 Walton Court,31,34,Backordered,50
3,71-594-6552,Long Grain Rice,Grains & Pulses,63-492-7603,Brightbean,12,59,62,1.5,2024-12-08,2025-02-19,2024-04-17,3 Westerfield Crossing,95,99,Active,-235
4,57-437-1828,Plum,Fruits & Vegetables,54-226-4308,Topicstorm,37,30,74,4.0,2024-07-03,2024-10-11,2024-10-05,15068 Scoville Court,62,25,Backordered,94

# Inventory Risk Score

In [31]:
data["Risk_Score"] = (
    (data["Stock_Quantity"] < data["Reorder_Level"]).astype(int)
    + (data["Sales_Volume"] > data["Stock_Quantity"]).astype(int)
    + (data["Days_to_Expiry"] < 15).astype(int)
)
data.head()

,Product_ID,Product_Name,Catagory,Supplier_ID,Supplier_Name,Stock_Quantity,Reorder_Level,Reorder_Quantity,Unit_Price,Date_Received,Last_Order_Date,Expiration_Date,Warehouse_Location,Sales_Volume,Inventory_Turnover_Rate,Status,Days_to_Expiry,Risk_Score
0,29-205-1132,Sushi Rice,Grains & Pulses,38-037-1699,Jaxnation,22,72,70,4.5,2024-08-16,2024-06-29,2024-09-19,48 Del Sol Trail,32,19,Discontinued,34,2
1,40-681-9981,Arabica Coffee,Beverages,54-470-2479,Feedmix,45,77,2,20.0,2024-11-01,2024-05-29,2024-05-08,36 3rd Place,85,1,Discontinued,-177,3
2,06-955-3428,Black Rice,Grains & Pulses,54-031-2945,Vinder,30,38,83,6.0,2024-08-03,2024-06-10,2024-09-22,3296 Walton Court,31,34,Backordered,50,2
3,71-594-6552,Long Grain Rice,Grains & Pulses,63-492-7603,Brightbean,12,59,62,1.5,2024-12-08,2025-02-19,2024-04-17,3 Westerfield Crossing,95,99,Active,-235,3
4,57-437-1828,Plum,Fruits & Vegetables,54-226-4308,Topicstorm,37,30,74,4.0,2024-07-03,2024-10-11,2024-10-05,15068 Scoville Court,62,25,Backordered,94,1